In [1]:
from XRDXRFutils import DataSXRF, SpectraSXRF, FluorescenceSXRF
datadir = "/home/rosario/xmimsim/syntetic/Giulia_suited/outdata"
dsxrf = DataSXRF()
dsxrf.set_nbins(1024)

In [2]:
%%time
synt_data = dsxrf.read(datadir)

Reading SXRF data from /home/rosario/xmimsim/syntetic/Giulia_suited/outdata
CPU times: user 162 ms, sys: 69.4 ms, total: 231 ms
Wall time: 9.83 s


In [15]:
#read a single spectra
sxrf = SpectraSXRF()
sxrf.set_nbins(1024)
xmso_file = "xsimspe_Fe-80.05-Mn-10.59-K-0.4-Ca-8.97_0.000111_hydro0.000475_live-time0.015_d-samp-det1.5_d-samp-src6_slit0.001_photons100000.xmso"
synt = sxrf.from_file("/home/rosario/xmimsim/syntetic/Giulia_suited/FeMnCaK/outdata/Fe-Mn-K-Ca/" + xmso_file)
print(synt.counts.shape)
print(synt.energy.shape)
for l in synt.fluorescence_lines:
    print(l.symbol, l.lines)

(1024,)
(1024,)
Ar {'K': 3.0091259999999997, 'L': 0, 'others': 0}
K {'K': 0.5248212, 'L': 0, 'others': 0}
Ca {'K': 18.509862, 'L': 0, 'others': 0}
Mn {'K': 47.09059, 'L': 0, 'others': 0}
Fe {'K': 364.61719999999997, 'L': 0, 'others': 0}
Pb {'K': 0, 'L': 229.24215005124003, 'others': 7.145690757264799}


In [3]:
dir(synt_data)

['_Data__resample_x',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__read__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__slotnames__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_labels',
 'calibrate_from_file',
 'f_resample_y',
 'fce_calibration',
 'get_data_and_labels',
 'load_h5',
 'metadata',
 'name',
 'nbins',
 'process_file',
 'read',
 'read_params',
 'resample',
 'save_h5',
 'set_nbins',
 'shape',
 'spe_objs',
 'x']

In [4]:
dir(synt_data.spe_objs[0])

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'channel',
 'counts',
 'energy',
 'fluorescence_lines',
 'from_array',
 'from_file',
 'get_fluorescence_lines',
 'get_metadata',
 'nbins',
 'reflayer_atomic_num',
 'reflayer_thickness',
 'resample',
 'set_nbins',
 'sublayer_thickness',
 'weight_fractions']

In [5]:
import numpy as np
symbols = ["Ca", "Cu", "Fe", "Mn", "Pb"]
lines = ["K", "K", "K", "K", "L"]

In [6]:
%%time
synt_data_Giulia = synt_data.get_data_and_labels(symbols, lines)

CPU times: user 3.65 ms, sys: 3.67 ms, total: 7.32 ms
Wall time: 6.61 ms


In [7]:
print(f"data shape: {synt_data.data.shape}")
print(f"labels shape: {synt_data.labels.shape}")
print(synt_data.labels)

data shape: (875, 1024)
labels shape: (875, 5)
[[   0.            0.            0.           27.89937    1022.91231164]
 [   0.            0.            0.          110.1842      964.41207148]
 [   0.            0.            0.           52.64975    1006.62408571]
 ...
 [   0.            0.          419.3577       12.447786    798.13735123]
 [   0.            0.          124.07805      25.36613     927.53803275]
 [   0.            0.          112.84467      19.892509    971.87732955]]


In [13]:
#From ElGreco for Giulia
datadir = "/home/rosario/xmimsim/syntetic/Giulia_suited/FromElGreco/outdata"
dsxrf_ElGiulia = DataSXRF()
dsxrf_ElGiulia.set_nbins(1024)
synt_data_ElGiulia = dsxrf.read(datadir)
synt_data_ElGiulia = synt_data_ElGiulia.get_data_and_labels(symbols, lines)
print(synt_data_ElGiulia.data.shape, synt_data_ElGiulia.labels.shape)
time_correction = 0.15
synt_data_ElGiulia.data = synt_data_ElGiulia.data * time_correction
synt_data_ElGiulia.labels = synt_data_ElGiulia.labels * time_correction

Reading SXRF data from /home/rosario/xmimsim/syntetic/Giulia_suited/FromElGreco/outdata
(297, 1024) (297, 5)


In [14]:
datacube = np.concatenate((synt_data_Giulia.data, synt_data_ElGiulia.data))
datacube_labels = np.concatenate((synt_data_Giulia.labels, synt_data_ElGiulia.labels))
print(datacube.shape)
print(datacube.shape)

(594, 1024)
(594, 1024)


In [15]:
np.save("/home/rosario/xmimsim/syntetic/datacube.npy", datacube)
np.save("/home/rosario/xmimsim/syntetic/datacube_labels.npy", datacube_labels)